Detect primary language automatically.

diff --git a/build b/build
--- a/build
+++ b/build
@@ -16,18 +16,23 @@ else
 	NC=''
 fi
 
-echo
-echo -e "${RED}Primary language is $PRIMARY_LANGUAGE.${NC}"
 
 # Check this is run from a reasonable directory.
 # (Advanced users can run /bin/bash as a Docker target command.)
-if [[ ! -e index.$PRIMARY_LANGUAGE.adoc ]]; then
-	echo >&2 "There is no index.$PRIMARY_LANGUAGE.adoc file in this directory."
+if ! git ls-files --error-unmatch 'index.??.adoc' > /dev/null; then
+	echo >&2 "There is no index.en.adoc file in this directory."
 	echo >&2
 	echo >&2 "Check you are running this from the top-level of your document,"
-	echo >&2 "and that there is an $PRIMARY_LANGUAGE source document called index.$PRIMARY_LANGUAGE.adoc."
+	echo >&2 "and that there is a source document called index.en.adoc."
+	echo >&2
+	echo >&2 "(Substitute en with another two-letter language code as required.)"
 	exit 1
 fi
+
+PRIMARY_LANGUAGE=$(git ls-files 'index.??.adoc' | cut -d. -f 2)
+
+echo
+echo -e "${RED}Primary language is $PRIMARY_LANGUAGE.${NC}"
 
 # Clean any old files
 echo "Removing files ignored by Git"
